# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conjecture_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=100)),
                ('output_list', models.TextField()),
                ('number_of_div', models.IntegerField()),
                ('number_of_mul', models.IntegerField()),
            ],
        ),
    ]
