# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjecture_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjecture_model',
            name='number_of_div',
        ),
        migrations.RemoveField(
            model_name='conjecture_model',
            name='number_of_mul',
        ),
        migrations.AlterField(
            model_name='conjecture_model',
            name='number',
            field=models.IntegerField(),
        ),
    ]
